name: 'Terraform'

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    uses: szpeter920/templates/.github/workflows/terraform.yml@main
    with:
      environment_name: 'dev'
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
